# Generated by Django 4.1.10 on 2023-11-20 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_nama_product_product_satuan'),
        ('user', '0002_user_username_alter_user_password'),
        ('sells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selling_in',
            name='no_faktur_distribusi',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='selling_in',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='selling_in',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selling_in',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='selling_in_out',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='selling_in_out',
            name='selling_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selling_in_out',
            name='selling_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selling_in_out',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='selling_out',
            name='no_faktur_distribusi',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='selling_out',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='selling_out',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selling_out',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
