# Generated by Django 4.1.10 on 2023-11-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nama_product',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='satuan',
            field=models.BooleanField(max_length=100, null=True),
        ),
    ]
