# Generated by Django 4.1.10 on 2023-11-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_nama_product_product_satuan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='satuan',
            field=models.IntegerField(default=0),
        ),
    ]
